#name: Rust
#
#on:
#  push:
#    branches: [ "dev" ]
#  pull_request:
#    branches: [ "main" ]
#
#env:
#  CARGO_TERM_COLOR: always
#
#jobs:
#  build:
#
#    runs-on: ubuntu-latest
#
#    steps:
#    - uses: actions/checkout@v5
#    - name: Build
#      run: cargo build
#    - name: Run tests
#      run: cargo test
